//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspired.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gen_UserMaster
    {
        public Gen_UserMaster()
        {
            this.Inv_MaterialNotes = new HashSet<Inv_MaterialNotes>();
            this.Inv_MaterialNotes1 = new HashSet<Inv_MaterialNotes>();
            this.Inv_DocumentMaster = new HashSet<Inv_DocumentMaster>();
            this.Inv_StockMaster = new HashSet<Inv_StockMaster>();
            this.Inv_StockTran = new HashSet<Inv_StockTran>();
        }
    
        public int Id { get; set; }
        public string UserName { get; set; }
        public int Company_Id { get; set; }
        public Nullable<int> Branch_Id { get; set; }
        public string Status { get; set; }
    
        public virtual Gen_BranchMaster Gen_BranchMaster { get; set; }
        public virtual Gen_CompanyMaster Gen_CompanyMaster { get; set; }
        public virtual ICollection<Inv_MaterialNotes> Inv_MaterialNotes { get; set; }
        public virtual ICollection<Inv_MaterialNotes> Inv_MaterialNotes1 { get; set; }
        public virtual ICollection<Inv_DocumentMaster> Inv_DocumentMaster { get; set; }
        public virtual ICollection<Inv_StockMaster> Inv_StockMaster { get; set; }
        public virtual ICollection<Inv_StockTran> Inv_StockTran { get; set; }
    }
}
