//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspired.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gen_BranchMaster
    {
        public Gen_BranchMaster()
        {
            this.FAS_AccountMaster = new HashSet<FAS_AccountMaster>();
            this.Inv_MaterialBranchSpec = new HashSet<Inv_MaterialBranchSpec>();
            this.Inv_MaterialDiscount = new HashSet<Inv_MaterialDiscount>();
            this.Inv_WarehouseMaster = new HashSet<Inv_WarehouseMaster>();
            this.Inv_MaterialBranch = new HashSet<Inv_MaterialBranch>();
            this.Gen_UserMaster = new HashSet<Gen_UserMaster>();
        }
    
        public int Id { get; set; }
        public int Company_Id { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<FAS_AccountMaster> FAS_AccountMaster { get; set; }
        public virtual Gen_CompanyMaster Gen_CompanyMaster { get; set; }
        public virtual ICollection<Inv_MaterialBranchSpec> Inv_MaterialBranchSpec { get; set; }
        public virtual ICollection<Inv_MaterialDiscount> Inv_MaterialDiscount { get; set; }
        public virtual ICollection<Inv_WarehouseMaster> Inv_WarehouseMaster { get; set; }
        public virtual ICollection<Inv_MaterialBranch> Inv_MaterialBranch { get; set; }
        public virtual ICollection<Gen_UserMaster> Gen_UserMaster { get; set; }
    }
}
