//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspired.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gen_LookupItem
    {
        public Gen_LookupItem()
        {
            this.Inv_CategoryMaster = new HashSet<Inv_CategoryMaster>();
            this.Inv_MaterialDiscount = new HashSet<Inv_MaterialDiscount>();
            this.Inv_MaterialPrice = new HashSet<Inv_MaterialPrice>();
            this.Inv_MaterialSupplier = new HashSet<Inv_MaterialSupplier>();
            this.Inv_MaterialSpecification = new HashSet<Inv_MaterialSpecification>();
            this.Inv_WarehouseMaster = new HashSet<Inv_WarehouseMaster>();
            this.Inv_MaterialCategory = new HashSet<Inv_MaterialCategory>();
            this.Inv_MaterialMaster = new HashSet<Inv_MaterialMaster>();
            this.Inv_MaterialAlternateRelative = new HashSet<Inv_MaterialAlternateRelative>();
            this.FAS_AccountMaster = new HashSet<FAS_AccountMaster>();
            this.Inv_MaterialNotes = new HashSet<Inv_MaterialNotes>();
            this.Inv_MaterialNotes1 = new HashSet<Inv_MaterialNotes>();
        }
    
        public int Id { get; set; }
        public int LookupType_Id { get; set; }
        public Nullable<int> LookupGroup_Id { get; set; }
        public string Description { get; set; }
        public int Ordinal { get; set; }
        public bool IsOther { get; set; }
        public bool IsHidden { get; set; }
        public int Company_Id { get; set; }
        public int User_Id { get; set; }
        public System.DateTime Last_update { get; set; }
    
        public virtual Gen_CompanyMaster Gen_CompanyMaster { get; set; }
        public virtual ICollection<Inv_CategoryMaster> Inv_CategoryMaster { get; set; }
        public virtual ICollection<Inv_MaterialDiscount> Inv_MaterialDiscount { get; set; }
        public virtual ICollection<Inv_MaterialPrice> Inv_MaterialPrice { get; set; }
        public virtual ICollection<Inv_MaterialSupplier> Inv_MaterialSupplier { get; set; }
        public virtual ICollection<Inv_MaterialSpecification> Inv_MaterialSpecification { get; set; }
        public virtual ICollection<Inv_WarehouseMaster> Inv_WarehouseMaster { get; set; }
        public virtual Gen_LookupType Gen_LookupType { get; set; }
        public virtual ICollection<Inv_MaterialCategory> Inv_MaterialCategory { get; set; }
        public virtual Gen_LookupGroup Gen_LookupGroup { get; set; }
        public virtual ICollection<Inv_MaterialMaster> Inv_MaterialMaster { get; set; }
        public virtual ICollection<Inv_MaterialAlternateRelative> Inv_MaterialAlternateRelative { get; set; }
        public virtual ICollection<FAS_AccountMaster> FAS_AccountMaster { get; set; }
        public virtual ICollection<Inv_MaterialNotes> Inv_MaterialNotes { get; set; }
        public virtual ICollection<Inv_MaterialNotes> Inv_MaterialNotes1 { get; set; }
    }
}
