//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspired.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InspiredEntities : DbContext
    {
        public InspiredEntities()
            : base("name=InspiredEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Gen_BranchMaster> Gen_BranchMaster { get; set; }
        public virtual DbSet<Gen_CompanyMaster> Gen_CompanyMaster { get; set; }
        public virtual DbSet<Gen_LookupType> Gen_LookupType { get; set; }
        public virtual DbSet<Inv_CategoryMaster> Inv_CategoryMaster { get; set; }
        public virtual DbSet<Inv_MaterialDiscount> Inv_MaterialDiscount { get; set; }
        public virtual DbSet<Inv_MaterialDocument> Inv_MaterialDocument { get; set; }
        public virtual DbSet<Inv_MaterialPackaging> Inv_MaterialPackaging { get; set; }
        public virtual DbSet<Inv_MaterialPrice> Inv_MaterialPrice { get; set; }
        public virtual DbSet<Inv_WarehouseMaster> Inv_WarehouseMaster { get; set; }
        public virtual DbSet<Inv_MaterialBranchSpec> Inv_MaterialBranchSpec { get; set; }
        public virtual DbSet<Inv_MaterialNotes> Inv_MaterialNotes { get; set; }
        public virtual DbSet<Inv_MaterialSupplier> Inv_MaterialSupplier { get; set; }
        public virtual DbSet<Inv_MaterialBOM> Inv_MaterialBOM { get; set; }
        public virtual DbSet<Inv_MaterialBranch> Inv_MaterialBranch { get; set; }
        public virtual DbSet<Gen_UserMaster> Gen_UserMaster { get; set; }
        public virtual DbSet<Inv_MaterialCategory> Inv_MaterialCategory { get; set; }
        public virtual DbSet<Inv_MaterialSpecification> Inv_MaterialSpecification { get; set; }
        public virtual DbSet<Gen_LookupItem> Gen_LookupItem { get; set; }
        public virtual DbSet<Gen_LookupGroup> Gen_LookupGroup { get; set; }
        public virtual DbSet<Inv_MaterialSpares> Inv_MaterialSpares { get; set; }
        public virtual DbSet<Inv_MaterialMaster> Inv_MaterialMaster { get; set; }
        public virtual DbSet<Inv_MaterialAlternateRelative> Inv_MaterialAlternateRelative { get; set; }
        public virtual DbSet<FAS_AccountMaster> FAS_AccountMaster { get; set; }
    }
}
