//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspired.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_MaterialMaster
    {
        public Inv_MaterialMaster()
        {
            this.Inv_MaterialBOM = new HashSet<Inv_MaterialBOM>();
            this.Inv_MaterialBOM1 = new HashSet<Inv_MaterialBOM>();
            this.Inv_MaterialBranch = new HashSet<Inv_MaterialBranch>();
            this.Inv_MaterialBranchSpec = new HashSet<Inv_MaterialBranchSpec>();
            this.Inv_MaterialCategory = new HashSet<Inv_MaterialCategory>();
            this.Inv_MaterialDiscount = new HashSet<Inv_MaterialDiscount>();
            this.Inv_MaterialDocument = new HashSet<Inv_MaterialDocument>();
            this.Inv_MaterialPackaging = new HashSet<Inv_MaterialPackaging>();
            this.Inv_MaterialPrice = new HashSet<Inv_MaterialPrice>();
            this.Inv_MaterialSpecification = new HashSet<Inv_MaterialSpecification>();
            this.Inv_MaterialSupplier = new HashSet<Inv_MaterialSupplier>();
            this.MaterialSpares = new HashSet<Inv_MaterialSpares>();
            this.SpareItem = new HashSet<Inv_MaterialSpares>();
            this.AlternateRelativeItemCollection = new HashSet<Inv_MaterialAlternateRelative>();
            this.AlternateRelativeItemId = new HashSet<Inv_MaterialAlternateRelative>();
            this.Inv_MaterialNotes = new HashSet<Inv_MaterialNotes>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public string SKU_Number { get; set; }
        public string Long_Description { get; set; }
        public string Overview { get; set; }
        public Nullable<int> UOM { get; set; }
        public Nullable<decimal> Margin_Percent { get; set; }
        public Nullable<bool> Batch_YN { get; set; }
        public Nullable<bool> Serial_YN { get; set; }
        public Nullable<bool> Location_YN { get; set; }
        public Nullable<int> Shelf_Life { get; set; }
        public string Barcode { get; set; }
        public Nullable<int> Max_Level { get; set; }
        public Nullable<int> Min_Level { get; set; }
        public Nullable<int> Re_order_Level { get; set; }
        public Nullable<int> Lead_Time { get; set; }
        public Nullable<decimal> NETT_Price { get; set; }
        public Nullable<decimal> Sale_Price { get; set; }
        public Nullable<decimal> Cost_Price { get; set; }
        public Nullable<decimal> LIFO_Price { get; set; }
        public Nullable<decimal> FIFO_Price { get; set; }
        public Nullable<decimal> WA_Price { get; set; }
        public Nullable<int> MCarton_Quantity { get; set; }
        public Nullable<decimal> MCarton_Length { get; set; }
        public Nullable<decimal> MCarton_Width { get; set; }
        public Nullable<decimal> MCarton_Height { get; set; }
        public Nullable<decimal> MCarton_Gross_Weight { get; set; }
        public Nullable<decimal> MCarton_NETT_Weight { get; set; }
        public string Status { get; set; }
        public int Company_Id { get; set; }
        public Nullable<int> User_Id { get; set; }
        public Nullable<System.DateTime> Last_Updated { get; set; }
    
        public virtual Gen_CompanyMaster Gen_CompanyMaster { get; set; }
        public virtual Gen_LookupItem Gen_LookupItem { get; set; }
        public virtual ICollection<Inv_MaterialBOM> Inv_MaterialBOM { get; set; }
        public virtual ICollection<Inv_MaterialBOM> Inv_MaterialBOM1 { get; set; }
        public virtual ICollection<Inv_MaterialBranch> Inv_MaterialBranch { get; set; }
        public virtual ICollection<Inv_MaterialBranchSpec> Inv_MaterialBranchSpec { get; set; }
        public virtual ICollection<Inv_MaterialCategory> Inv_MaterialCategory { get; set; }
        public virtual ICollection<Inv_MaterialDiscount> Inv_MaterialDiscount { get; set; }
        public virtual ICollection<Inv_MaterialDocument> Inv_MaterialDocument { get; set; }
        public virtual ICollection<Inv_MaterialPackaging> Inv_MaterialPackaging { get; set; }
        public virtual ICollection<Inv_MaterialPrice> Inv_MaterialPrice { get; set; }
        public virtual ICollection<Inv_MaterialSpecification> Inv_MaterialSpecification { get; set; }
        public virtual ICollection<Inv_MaterialSupplier> Inv_MaterialSupplier { get; set; }
        public virtual ICollection<Inv_MaterialSpares> MaterialSpares { get; set; }
        public virtual ICollection<Inv_MaterialSpares> SpareItem { get; set; }
        public virtual ICollection<Inv_MaterialAlternateRelative> AlternateRelativeItemCollection { get; set; }
        public virtual ICollection<Inv_MaterialAlternateRelative> AlternateRelativeItemId { get; set; }
        public virtual ICollection<Inv_MaterialNotes> Inv_MaterialNotes { get; set; }
    }
}
