//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspired.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_DocumentMaster
    {
        public string TRANS_TYPE { get; set; }
        public string DOC_CODE { get; set; }
        public string DOC_DESC { get; set; }
        public decimal START_NO { get; set; }
        public decimal LAST_NO { get; set; }
        public bool STATUS { get; set; }
        public int COMPANY_ID { get; set; }
        public Nullable<int> USER_ID { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE { get; set; }
    
        public virtual Gen_CompanyMaster Gen_CompanyMaster { get; set; }
        public virtual Gen_UserMaster Gen_UserMaster { get; set; }
    }
}
