//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspired.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_MaterialBranch
    {
        public int Id { get; set; }
        public int Item_Id { get; set; }
        public int Branch_Id { get; set; }
        public string Description { get; set; }
        public string Long_Description { get; set; }
        public string Overview { get; set; }
        public string SKU_Number { get; set; }
        public Nullable<decimal> NETT_Price { get; set; }
        public Nullable<decimal> Sale_Price { get; set; }
        public Nullable<bool> Batch_YN { get; set; }
        public Nullable<bool> Serial_YN { get; set; }
        public Nullable<bool> Location_YN { get; set; }
        public string Status { get; set; }
        public int Company_Id { get; set; }
        public Nullable<int> User_Id { get; set; }
        public Nullable<System.DateTime> Last_Updated { get; set; }
    
        public virtual Gen_BranchMaster Gen_BranchMaster { get; set; }
        public virtual Gen_CompanyMaster Gen_CompanyMaster { get; set; }
        public virtual Inv_MaterialMaster Inv_MaterialMaster { get; set; }
    }
}
