//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspired.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_MaterialDiscount
    {
        public int Id { get; set; }
        public Nullable<int> Customer_Type { get; set; }
        public Nullable<int> Customer_Id { get; set; }
        public Nullable<int> Branch_Id { get; set; }
        public Nullable<int> Group_Id { get; set; }
        public Nullable<int> Type_Id { get; set; }
        public Nullable<int> Category_Id { get; set; }
        public Nullable<int> SubCategory_Id { get; set; }
        public Nullable<int> Make_Id { get; set; }
        public Nullable<int> Model_Number_Id { get; set; }
        public Nullable<int> Item_Id { get; set; }
        public decimal Discount { get; set; }
        public string Based_On { get; set; }
        public int From_Qty { get; set; }
        public int To_Qty { get; set; }
        public int Price_Type { get; set; }
        public int Company_Id { get; set; }
        public int User_Id { get; set; }
        public System.DateTime Last_Updated { get; set; }
    
        public virtual FAS_AccountMaster FAS_AccountMaster { get; set; }
        public virtual Gen_BranchMaster Gen_BranchMaster { get; set; }
        public virtual Gen_CompanyMaster Gen_CompanyMaster { get; set; }
        public virtual Inv_MaterialMaster Inv_MaterialMaster { get; set; }
        public virtual Inv_CategoryMaster Inv_CategoryMaster { get; set; }
        public virtual Inv_CategoryMaster Inv_CategoryMaster1 { get; set; }
        public virtual Inv_CategoryMaster Inv_CategoryMaster2 { get; set; }
        public virtual Inv_CategoryMaster Inv_CategoryMaster3 { get; set; }
        public virtual Inv_CategoryMaster Inv_CategoryMaster4 { get; set; }
        public virtual Inv_CategoryMaster Inv_CategoryMaster5 { get; set; }
        public virtual Gen_LookupItem Gen_LookupItem { get; set; }
    }
}
