//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspired.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_StockMaster
    {
        public int ITEM_ID { get; set; }
        public int WHS_ID { get; set; }
        public string BATCH_NO { get; set; }
        public Nullable<System.DateTime> OB_DT { get; set; }
        public decimal OB_QTY { get; set; }
        public decimal CB_QTY { get; set; }
        public string NOTES { get; set; }
        public Nullable<decimal> WA_PRC { get; set; }
        public Nullable<decimal> FIFO_PRC { get; set; }
        public Nullable<decimal> LIFO_PRC { get; set; }
        public int COMPANY_ID { get; set; }
        public Nullable<int> USER_ID { get; set; }
        public Nullable<System.DateTime> LAST_UPDATED { get; set; }
    
        public virtual Gen_CompanyMaster Gen_CompanyMaster { get; set; }
        public virtual Gen_UserMaster Gen_UserMaster { get; set; }
        public virtual Inv_MaterialMaster Inv_MaterialMaster { get; set; }
        public virtual Inv_WarehouseMaster Inv_WarehouseMaster { get; set; }
    }
}
