//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspired.DomainClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_MaterialNotes
    {
        public int Id { get; set; }
        public int Item_Id { get; set; }
        public int Accd_Key { get; set; }
        public string Taken_By { get; set; }
        public System.DateTime Entry_date { get; set; }
        public string Notes { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> Expiry_Date { get; set; }
        public string ToBe_Actioned_By { get; set; }
        public Nullable<System.DateTime> Action_Date { get; set; }
        public int Company_Id { get; set; }
        public int User_Id { get; set; }
        public System.DateTime Last_Updated { get; set; }
        public int Priority_Flg { get; set; }
    
        public virtual FAS_AccountMaster FAS_AccountMaster { get; set; }
        public virtual Gen_CompanyMaster Gen_CompanyMaster { get; set; }
        public virtual Inv_MaterialMaster Inv_MaterialMaster { get; set; }
        public virtual Gen_LookupItem Gen_LookupItem { get; set; }
    }
}
