//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspired.DomainClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_MaterialPackaging
    {
        public int Item_Id { get; set; }
        public int Box_Number { get; set; }
        public Nullable<decimal> Box_Length { get; set; }
        public Nullable<decimal> Box_Width { get; set; }
        public Nullable<decimal> Box_Height { get; set; }
        public Nullable<decimal> Box_Gross_Weight { get; set; }
        public Nullable<decimal> Box_NETT_Weight { get; set; }
        public int Company_Id { get; set; }
        public Nullable<int> User_Id { get; set; }
        public Nullable<System.DateTime> Last_Updated { get; set; }
    
        public virtual Gen_CompanyMaster Gen_CompanyMaster { get; set; }
        public virtual Inv_MaterialMaster Inv_MaterialMaster { get; set; }
    }
}
